export const typeAction = {
    XEM_CAN_BO: 'XEM_CAN_BO',
    XEM_NHOM_QUYEN: 'XEM_NHOM_QUYEN',
    XEM_SINH_VIEN: 'XEM_SINH_VIEN',
    XEM_MENU: 'XEM_MENU',
    XEM_TIN_TUC: 'XEM_TIN_TUC',
    XEM_CHUYEN_MUC_TIN_TUC: 'XEM_CHUYEN_MUC_TIN_TUC',
    XEM_GOP_Y: 'XEM_GOP_Y'
}
